services:
  portfolio:
    image: node_mau_portafolio:0.0.0
    network_mode: host
    volumes:
      - ./:/app

  portfolio_prod:
    extends: portfolio
    profiles: ["prod"]
    container_name: portfolio_prod
    command: >
      sh -c 'tail -f /dev/null'
